name: Always Successful

# Triggers the workflow on push or pull request events but only for the "main" branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is named "always-passes"
  always-passes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # This step just prints a message to the log.
      # Since 'echo' always exits with a success code (0), this job will never fail.
      - name: Always Pass
        run: echo "This job is designed to always pass!"
